### ISSUE TITLE
Reorganize project

### ISSUE THREAD

**Issue by Morgul** [SkewedAspect/rfi-webgl-client#41]
The current project has some issues with layout, and I think browserify causes more issues than it solves. Here is the proposal:

* [x] Add a browserify/Grunt build system to `rfi-physics`, and commit the built files to the repo.
* [x] Remove browserify from the client.
* [x] Move things around to the following directory structure:

```
.
├── src
│   ├── less 
│   │   └── sleekspace 
│   ├──lib 
│   │   ├── config 
│   │   ├── content
│   │   ├── entities
│   │   │   └── behaviors
│   │   ├── input 
│   │   ├── logging 
│   │   ├── network 
│   │   ├── physics 
│   │   └── storage 
│   ├── ui 
│   │   ├── game
│   │   ├── latency
│   │   └── login
│   ├── vendor
│   ├── app.js 
│   ├── externals.js 
│   └── index.html
├── content 
│   ├── fonts
│   ├── models
│   └── scenes
├── tests
├── .bowerrc 
├── .gitignore
├── .travis.yml
├── bower.json
├── Gruntfile.js
├── karma-config.js
├── LICENSE
├── package.json
└── Readme.md
```

/cc @SkewedAspect/developers Thoughts?

**Comment by Morgul** [comment]
@whitelynx, @Burstaholic: I updated the new project layout I'm thinking about. a few talking points: 
* should `less` live under `ui`?
* should it be `src`, or `client` (which I prefer in projects with a server and client in the same repo).
* is `lib` a good name? Normally I use `components`, but that doesn't see appropriate here...

**Comment by Burstaholic** [comment]
Basically, I like your proposal. The names you went with in the diagram make the most sense to me.
